[metadata]
name = "saptecheddarkfox"
author = "EdenEast"
origin_url = "https://github.com/EdenEast/nightfox.nvim"

[colors]
foreground = "#FFFFFF"
background = "#00144A"
cursor_bg = "#FFFFFF"
cursor_border = "#FFFFFF"
cursor_fg = "#00144A"
compose_cursor = '#cc00dc'
selection_bg = "#FF8AF0"
selection_fg = "#FFFFFF"
scrollbar_thumb = "#FF8AF0"
split = "#1B90FF"
visual_bell = "#FFFFFF"
ansi = ["#5d36ff", "#cc00dc", "#049f9a", "#89d1ff", "#1b90ff", "#1b90ff", "#049f9a", "#ffffff"]
brights = ["#7554ff", "#d426e1", "#2aada9", "#9bd8ff", "#3da1ff", "#3da1ff", "#2aada9", "#ffffff"]

[colors.indexed]
16 = "#cc00dc"
17 = "#cc00dc"

[colors.tab_bar]
background = "#1B90FF"
inactive_tab_edge = "#1B90FF"
inactive_tab_edge_hover = "#C2FCEE"

[colors.tab_bar.active_tab]
bg_color = "#FF8AF0"
fg_color = "#00144A"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#C2FCEE"
fg_color = "#FFFFFF"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#2CE0BF"
fg_color = "#FFFFFF"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#00144A"
fg_color = "#FFFFFF"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#2CE0BF"
fg_color = "#FFFFFF"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

